### PR TITLE
NTUEEPLUS-15. Improve Appearance of Column Text

### PR DESCRIPTION
**Pull request by vwvwMM**
### What is this PR for?

indent every subsection
reduce white and gray part and it won't change in different view percent!
delete subtitle's subtitle
### What type of PR is it?
[Bug Fix | Improvement | Feature | Documentation | Hot Fix | Refactoring]
improvement
### Todos
* [ ] - No

### What is the Jira issue?

https://ntueeplus.atlassian.net/browse/NTUEEPLUS-15
### Screenshots (if appropriate)
150%:
image
100%:
image

### CODE REVIEW

**Comment by vwvwMM** [comment]
@featherchen 
here

**Comment by featherchen** [comment]
@vwvwMM  Thanks for contribution, I just wonder if we can delete the white place at the leftest of 100%, and if we can let the indent words align to the words below.

**Comment by noidname01** [comment]
> @vwvwMM Thanks for contribution, I just wonder if we can delete the white place at the leftest of 100%, and if we can let the indent words align to the words below.

@featherchen you say the area between the number title and the content?

**Comment by noidname01** [comment]
@vwvwMM  Remember to modify the title to fit the format.

**Comment by featherchen** [comment]
> @featherchen you say the area between the number title and the content?

@noidname01  Actually I mean that the space out of the leftest sidebar, but I think the space you mentioned is too big either.

**Comment by noidname01** [comment]
Oh @vwvwMM  remember to rebase the repo and solve the conflict.

**Comment by vwvwMM** [comment]
> @vwvwMM Thanks for contribution, I just wonder if we can delete the white place at the leftest of 100%, and if we can let the indent words align to the words below.
do you mean this?
image

**Comment by vwvwMM** [comment]
> > @vwvwMM Thanks for contribution, I just wonder if we can delete the white place at the leftest of 100%, and if we can let the indent words align to the words below.
> 
> @featherchen you say the area between the number title and the content?

that space is for longer title, i'm not sure if it can auto adjust the space base on the length of title

**Comment by noidname01** [comment]
> > > @vwvwMM Thanks for contribution, I just wonder if we can delete the white place at the leftest of 100%, and if we can let the indent words align to the words below.
> > 
> > 
> > @featherchen you say the area between the number title and the content?
> 
> that space is for longer title, i'm not sure if it can auto adjust the space base on the length of title

I think we won't have too long title, and I want to take a look what will it look like. I mean reduce that area.

**Comment by vwvwMM** [comment]
> > > > @vwvwMM Thanks for contribution, I just wonder if we can delete the white place at the leftest of 100%, and if we can let the indent words align to the words below.
> > > 
> > > 
> > > @featherchen you say the area between the number title and the content?
> > 
> > 
> > that space is for longer title, i'm not sure if it can auto adjust the space base on the length of title
> 
> I think we won't have too long title, and I want to take a look what will it look like. I mean reduce that area.

then the statement about maximum words i previous write in the PR will change(i just want to remind this, i'll reduce the space

**Comment by vwvwMM** [comment]
@noidname01  i let the title be aligned-center. It looks great i think. How about u?
image

**Comment by noidname01** [comment]
> @noidname01 i let the title be aligned-center. It looks great i think. How about u?
> image

Cool, But I think the white area is still a little bit too more.

**Comment by vwvwMM** [comment]
> > @noidname01 i let the title be aligned-center. It looks great i think. How about u?
> > image
> 
> Cool, But I think the white area is still a little bit too more.
where?

**Comment by noidname01** [comment]
> > > @noidname01 i let the title be aligned-center. It looks great i think. How about u?
> > > image
> > 
> > 
> > Cool, But I think the white area is still a little bit too more.
> > where?

Title

**Review by noidname01 — APPROVED** [review]
LGTM, maybe? XD

**Pull request merged**
