### PR TITLE
NTUEEPLUS-104. isLogin API return userimage

### PR DESCRIPTION
**Pull request by featherchen**
### What is this PR for?

return userimage  from isLogin
### What type of PR is it?
Improvement 

### Todos
* [ ] - None

### What is the Jira issue?

https://ntueeplus.atlassian.net/browse/NTUEEPLUS-104
### Screenshots (if appropriate)
Screenshot from 2021-08-16 16-08-09

### CODE REVIEW

**Comment by featherchen** [comment]
@Claude0311 Is it fine that I stored userimage in session ? I am afraid of that it will affect the efficiency.
@noidname01  Does this meet your goal ?

**Comment by noidname01** [comment]
So I need to get image from session?

**Comment by featherchen** [comment]
You can get userimage from respond, but I don't know how to modify the api doc.

**Review by Claude0311 — APPROVED** [review]
LGTM

**Pull request merged**
