### PR TITLE
NTUEEPLUS-29. career pages

### PR DESCRIPTION
**Pull request by vwvwMM**
### What is this PR for?

Create career pages, including career, recommendation, and recruitment
Among these, career is the main page which can reach in sidebar, the other two should click corresponding picture in career to reach
### What type of PR is it?
[Bug Fix | Improvement | Feature | Documentation | Hot Fix | Refactoring]
feature
### Todos
* [ ] - add and delete posts
* [ ] - let picture in recruitment could be dynamic

### What is the Jira issue?

https://ntueeplus.atlassian.net/browse/NTUEEPLUS-29
### Screenshots (if appropriate)
this is caeer page:  (the recruitment is shaking)
image

this is recruitment:
image
image
image

this is recommendation:
image
image

### CODE REVIEW

**Review by noidname01 — CHANGES_REQUESTED** [review]
I think the picture can put in assets

**Comment by vwvwMM** [comment]
> I think the pictures can put in assets

in assets img or icon?

**Comment by noidname01** [comment]
> > I think the pictures can put in assets
> 
> in assets img or icon?

img

**Comment by vwvwMM** [comment]
> > > I think the pictures can put in assets
> > 
> > 
> > in assets img or icon?
> 
> img

i realize how stupid my question is when i saw the files in icon😂😂😂

**Comment by vwvwMM** [comment]
@noidname01  done!!

**Review by noidname01 — APPROVED** [review]
LGTM

**Pull request merged**
